#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Com.Luminous.Pick.Resource", IsApplication=true)]

namespace Com.Luminous.Pick
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040005
			public const int bg_light_blue = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int dialog_bg = 2130968586;
			
			// aapt resource value: 0x7f040003
			public const int gray = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int holo_blue_bright = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int light_black = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int light_black_ = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int light_black_AA = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int light_gray = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int light_white_ = 2130968585;
			
			// aapt resource value: 0x7f040001
			public const int menu_bg = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int tab_bg = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050002
			public const int activity_horizontal_margin = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int activity_vertical_margin = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int photo_height = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int photo_width = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_hover = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_sel = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int checkbox_selected = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int checkbox_up = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_launcher = 2130837509;
			
			// aapt resource value: 0x7f020009
			public const int light_black_ = 2130837513;
			
			// aapt resource value: 0x7f020006
			public const int no_media = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int on_focus_checkbox = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int top_bar = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int btnGalleryOk = 2131230723;
			
			// aapt resource value: 0x7f080009
			public const int btnGalleryPick = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int btnGalleryPickMul = 2131230730;
			
			// aapt resource value: 0x7f080004
			public const int frmQueue = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int gridGallery = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int imgNoMedia = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int imgQueue = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int imgQueueMultiSelected = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int imgSinglePick = 2131230728;
			
			// aapt resource value: 0x7f080002
			public const int llBottomContainer = 2131230722;
			
			// aapt resource value: 0x7f080007
			public const int viewSwitcher = 2131230727;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int gallery = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int gallery_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int titlebar = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int action_settings = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int btn_ok = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int btn_pick = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int btn_pick_mul = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int hello_world = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int btn = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int title_bar = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
